server:
  port: 8080
spring:
  application:
    name: ingredientMicroservice
#  jpa:
#    generate-ddl: false
#    hibernate:
#      ddl-auto: none

  datasource:
    url: jdbc:postgresql://localhost:5432/Recipes_db
    username: postgres
    password: 100891
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 5
#  jpa:
#    hibernate:
#      ddl-auto: update
#  profiles:
#    active: dev
#
#logging:
#  level:
#    root: INFO
#
#server:
#  port: 8080
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"